/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_test_ServiceCalled */

#ifndef _Included_com_example_test_ServiceCalled
#define _Included_com_example_test_ServiceCalled
#ifdef __cplusplus
extern "C" {
#endif



/*
 * Class:     com_example_test_ServiceCalled
 * Method:    start
 * Signature: (Ljava/lang/String;ILjava/lang/String;)Z
 */
JNIEXPORT void JNICALL Java_com_example_test_ServiceCalled_start
  (JNIEnv *, jobject, jstring, jint, jstring);

/*
 * Class:     com_example_test_ServiceCalled
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_test_ServiceCalled_stop
  (JNIEnv *, jobject);

/*
 * Class:     com_example_test_ServiceCalled
 * Method:    sendMessageNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/util/List;)V
 */
JNIEXPORT jboolean JNICALL Java_com_example_test_ServiceCalled_sendMessageNative
  (JNIEnv *, jobject, jstring, jstring,jint , jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
