/******************************************************************************
  Copyright (c) 2015 by Baida.zhang(Tong.zhang)  - zt9788@126.com

Permission is hereby granted, free of charge, to any person obtaining a copy of
this software and associated documentation files (the "Software"), to deal in
the Software without restriction, including without limitation the rights to
use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies
of the Software, and to permit persons to whom the Software is furnished to do
so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_test_ServiceCalled */

#ifndef _Included_com_example_test_ServiceCalled
#define _Included_com_example_test_ServiceCalled
#ifdef __cplusplus
extern "C" {
#endif



/*
 * Class:     com_example_test_ServiceCalled
 * Method:    start
 * Signature: (Ljava/lang/String;ILjava/lang/String;)Z
 */
JNIEXPORT void JNICALL Java_com_example_test_ServiceCalled_start
  (JNIEnv *, jobject, jstring, jint, jstring);

/*
 * Class:     com_example_test_ServiceCalled
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_example_test_ServiceCalled_stop
  (JNIEnv *, jobject);

/*
 * Class:     com_example_test_ServiceCalled
 * Method:    sendMessageNative
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/util/List;)V
 */
JNIEXPORT jboolean JNICALL Java_com_example_test_ServiceCalled_sendMessageNative
  (JNIEnv *, jobject, jstring, jstring,jint , jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
